# For full config options, check the docs:
#    docs.serverless.com

# plugins:
#    - serverless-offline

service: theory-revamped-express-server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"
useDotenv: true

provider:
   name: aws
   runtime: nodejs12.x
   stage: dev
   region: ${AWS_REGION}
   environment:

   TABLE_NAME:
      Ref: songTable

   iamRoleStatements:
      - Effect: Allow
        Action:
           - dynamodb:DescribeTable
           - dynamodb:Query
           - dynamodb:Scan
           - dynamodb:GetItem
           - dynamodb:PutItem
           - dynamodb:UpdateItem
           - dynamodb:DeleteItem
        Resource:
           - "Fn::GetAtt": [songTable, Arn]

resources:
   Resources:
      SongTable:
         Type: AWS::DynamoDB::Table
         Properties:
            TableName: songTable
            AttributeDefinitions:
               - AttributeName: song_id
                 AttributeType: N
               - AttributeName: version
                 AttributeType: N
               - AttributeName: approved
                 AttributeType: S
            KeySchema:
               - AttributeName: song_id
                 KeyType: HASH
            GlobalSecondaryIndexes:
               GlobalSecondaryIndex:
                  IndexName: version-index
                  KeySchema:
                     - AttributeName: version
                       keyType: HASH
                     - AttributeName: approved
                       keyType: HASH

functions:
   express-handler:
      handler: packages/express-server/app.handler
      events:
         - http:
              path: /api
              method: ANY
              cors: true
         - http:
              path: /api/{any+}
              method: ANY
              cors: true
