# For full config options, check the docs:
#    docs.serverless.com

plugins:
   - serverless-offline

service: theory-revamped-express-server
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"

provider:
   name: aws
   runtime: nodejs12.x
   stage: dev
   region: us-east-1

functions:
   hello:
      handler: handler.hello
